# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 切割pdf

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'pdf/split-pdf.py'
          requirements: 'pdf/requirements.txt'
          upload_exe_with_name: 'split-pdf'
          options: --onefile, --name "split-pdf", --windowed, 
